networks:
  my-go-crud-net:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my-go-crud-net
    volumes:
      - db-data:/data/db

  api:
    build: .
    ports:
      - 3333:3333
    networks:
      - my-go-crud-net
